// Package deployssh runs deploy/install.sh on a remote VPS over SSH,
// non-interactively - see install.sh's ask/ask_secret helpers, which skip
// prompting for any variable already present in the environment. This
// package is the thing that pre-sets them all and streams the script's
// output back, one line at a time, via Callback.
package deployssh

import (
	"bufio"
	"fmt"
	"io"
	"net"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/ssh"
)

const (
	connectTimeout     = 15 * time.Second
	deployTimeout      = 15 * time.Minute
	tcpKeepAlivePeriod = 15 * time.Second

	defaultDeployScriptURL = "https://raw.githubusercontent.com/wlruscfd/openflux-deploy/main/install.sh"
)

// keepaliveInterval is a var (not a const) so a test can shrink it instead
// of waiting out the real interval.
var keepaliveInterval = 30 * time.Second

// SSHTarget describes how to reach and authenticate to the VPS.
type SSHTarget struct {
	Host     string
	Port     int
	Username string

	// AuthMethod is "password" or "key".
	AuthMethod    string
	Password      string
	PrivateKeyPEM string
	Passphrase    string // only used if PrivateKeyPEM is itself encrypted

	// KnownHostKeyFingerprint pins the server's host key (ssh.FingerprintSHA256
	// form) after a first successful connect. Leave empty on the very first
	// deploy to a given server; Callback.OnHostKeyFingerprint reports the
	// fingerprint to save for next time either way.
	KnownHostKeyFingerprint string
}

// DeployOptions mirrors install.sh's own questions - see deploy/install.sh's
// ask/ask_secret calls for the exact variable names these become.
type DeployOptions struct {
	// DeployScriptURL defaults to the openflux-deploy repo's raw install.sh
	// if left blank.
	DeployScriptURL string

	RepoURL string
	GitRef  string

	TLSMode  string // "domain" or "ip"
	Domain   string
	Email    string
	ServerIP string

	// AdminToken/DBPassword are generated by the caller (not left for
	// install.sh to invent) so it's known immediately, before the deploy
	// even starts - see mobile/deploy.go's caller for why.
	AdminToken string
	DBPassword string

	RegisterNode bool
	NodeName     string
	NodeMaxKeys  int
	// RunNodeHere, when RegisterNode is true, also builds and runs the exit
	// node right on this same server as a systemd service instead of just
	// registering it in the database - see RUN_NODE_HERE in install.sh.
	RunNodeHere bool
}

// Callback receives live progress from Deploy.
type Callback interface {
	// OnLog is called once per line of the remote script's stdout/stderr,
	// in order, as it's produced.
	OnLog(line string)
	// OnHostKeyFingerprint is called exactly once, right after the SSH
	// handshake completes, whether or not a KnownHostKeyFingerprint was
	// supplied - the caller should persist it for next time.
	OnHostKeyFingerprint(fingerprint string)
	// OnDeployResult is called once, near the end of a successful run, with
	// the values install.sh prints in its final machine-readable summary
	// line (see resultLinePrefix). adminToken echoes back opts.AdminToken;
	// panelURL and nodeToken are not otherwise known to the caller -
	// nodeToken in particular is generated remotely and, like every other
	// token this API issues, shown exactly once - so this is the only
	// chance to capture it. nodeToken is empty if opts.RegisterNode was
	// false or node registration failed (install.sh warns but doesn't
	// abort in that case).
	OnDeployResult(panelURL, adminToken, nodeToken string)
}

// Deploy connects to target and runs install.sh there with opts applied as
// pre-set environment variables, so none of the script's prompts fire. It
// blocks until the remote command finishes (or deployTimeout elapses) and
// returns a non-nil error if the script exited non-zero or the connection
// failed at any point.
func Deploy(target SSHTarget, opts DeployOptions, cb Callback) error {
	if cb == nil {
		cb = noopCallback{}
	}

	authMethod, err := buildAuthMethod(target)
	if err != nil {
		return fmt.Errorf("build ssh auth: %w", err)
	}

	var reportedFingerprint string
	config := &ssh.ClientConfig{
		User:    target.Username,
		Auth:    []ssh.AuthMethod{authMethod},
		Timeout: connectTimeout,
		HostKeyCallback: func(hostname string, remote net.Addr, key ssh.PublicKey) error {
			fp := ssh.FingerprintSHA256(key)
			reportedFingerprint = fp
			if target.KnownHostKeyFingerprint != "" && target.KnownHostKeyFingerprint != fp {
				return fmt.Errorf(
					"host key for %s changed: expected %s, got %s - remove and re-add this server if this is expected (rebuild, reinstall), otherwise treat this as a possible attack and do not proceed",
					hostname, target.KnownHostKeyFingerprint, fp,
				)
			}
			return nil
		},
	}

	addr := fmt.Sprintf("%s:%d", target.Host, target.Port)
	// ssh.Dial's own net.Dial leaves OS-level TCP keepalive off. The
	// keepalive@openflux goroutine below only puts traffic on a connection
	// that's still actually there - it does nothing for one the kernel
	// thinks is fine but that's gone dead on the wire (a mobile network
	// swapping towers, a NAT that dropped the mapping without either side's
	// TCP stack noticing yet). A nonzero net.Dialer.KeepAlive turns on the
	// OS's own probing, which detects that case and fails the connection
	// outright instead of leaving it silently hung.
	tcpConn, err := (&net.Dialer{Timeout: connectTimeout, KeepAlive: tcpKeepAlivePeriod}).Dial("tcp", addr)
	if err != nil {
		return fmt.Errorf("dial %s: %w", addr, err)
	}
	sshConn, chans, reqs, err := ssh.NewClientConn(tcpConn, addr, config)
	if err != nil {
		tcpConn.Close()
		return fmt.Errorf("ssh handshake %s: %w", addr, err)
	}
	client := ssh.NewClient(sshConn, chans, reqs)
	defer client.Close()

	cb.OnHostKeyFingerprint(reportedFingerprint)

	// golang.org/x/crypto/ssh sends no keepalive traffic of its own, unlike
	// a normal ssh(1)/PuTTY client (which is why running install.sh by hand
	// over a plain SSH session doesn't hit this). install.sh's remote build
	// steps (go build ./cmd/controlplane, the exit-node binary) can run for
	// a minute or more with zero output on the channel - long enough for a
	// NAT/firewall on the path (a mobile carrier's, most likely, given
	// where this runs) to decide the idle connection is dead and drop it
	// silently. That surfaces here as session.Wait() returning
	// *ssh.ExitMissingError ("remote command exited without exit status or
	// exit signal") - the channel just vanished mid-command, not that the
	// remote command actually finished and reported anything. A periodic
	// global request keeps real traffic flowing over the connection so
	// nothing on the path ever considers it idle.
	stopKeepalive := make(chan struct{})
	defer close(stopKeepalive)
	go func() {
		ticker := time.NewTicker(keepaliveInterval)
		defer ticker.Stop()
		for {
			select {
			case <-stopKeepalive:
				return
			case <-ticker.C:
				client.SendRequest("keepalive@openflux", true, nil)
			}
		}
	}()

	session, err := client.NewSession()
	if err != nil {
		return fmt.Errorf("open ssh session: %w", err)
	}
	defer session.Close()

	stdout, err := session.StdoutPipe()
	if err != nil {
		return fmt.Errorf("stdout pipe: %w", err)
	}
	stderr, err := session.StderrPipe()
	if err != nil {
		return fmt.Errorf("stderr pipe: %w", err)
	}

	remoteCmd := buildRemoteCommand(opts)

	if err := session.Start(remoteCmd); err != nil {
		return fmt.Errorf("start remote command: %w", err)
	}

	var wg sync.WaitGroup
	wg.Add(2)
	go streamLines(stdout, cb, &wg)
	go streamLines(stderr, cb, &wg)

	done := make(chan error, 1)
	go func() {
		wg.Wait()
		done <- session.Wait()
	}()

	select {
	case err := <-done:
		if err != nil {
			return fmt.Errorf("install.sh failed: %w", err)
		}
		return nil
	case <-time.After(deployTimeout):
		session.Signal(ssh.SIGKILL)
		return fmt.Errorf("deploy timed out after %s", deployTimeout)
	}
}

func buildAuthMethod(target SSHTarget) (ssh.AuthMethod, error) {
	switch target.AuthMethod {
	case "key":
		var signer ssh.Signer
		var err error
		if target.Passphrase != "" {
			signer, err = ssh.ParsePrivateKeyWithPassphrase([]byte(target.PrivateKeyPEM), []byte(target.Passphrase))
		} else {
			signer, err = ssh.ParsePrivateKey([]byte(target.PrivateKeyPEM))
		}
		if err != nil {
			return nil, fmt.Errorf("parse private key: %w", err)
		}
		return ssh.PublicKeys(signer), nil
	case "password", "":
		return ssh.Password(target.Password), nil
	default:
		return nil, fmt.Errorf("unknown auth method %q", target.AuthMethod)
	}
}

// resultLinePrefix marks install.sh's one machine-readable output line
// (space-separated key=value pairs, appended after its human-readable
// summary) - see deploy/install.sh's final SUMMARY block. Lines with this
// prefix are reported via Callback.OnDeployResult instead of OnLog, since
// they're not meant for a human reading the deploy log.
const resultLinePrefix = "OPENFLUX_DEPLOY_RESULT "

func streamLines(r io.Reader, cb Callback, wg *sync.WaitGroup) {
	defer wg.Done()
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if fields, ok := strings.CutPrefix(line, resultLinePrefix); ok {
			reportDeployResult(fields, cb)
			continue
		}
		cb.OnLog(line)
	}
}

func reportDeployResult(fields string, cb Callback) {
	values := make(map[string]string)
	for _, tok := range strings.Fields(fields) {
		key, value, ok := strings.Cut(tok, "=")
		if !ok {
			continue
		}
		values[key] = value
	}
	cb.OnDeployResult(values["panel_url"], values["admin_token"], values["node_token"])
}

// buildRemoteCommand fetches install.sh and runs it with every DeployOptions
// field pre-exported (shell-quoted) so its ask/ask_secret helpers never
// prompt - see deploy/install.sh.
func buildRemoteCommand(opts DeployOptions) string {
	scriptURL := opts.DeployScriptURL
	if scriptURL == "" {
		scriptURL = defaultDeployScriptURL
	}

	env := map[string]string{
		"REPO_URL":      opts.RepoURL,
		"GIT_REF":       opts.GitRef,
		"TLS_MODE":      opts.TLSMode,
		"DOMAIN":        opts.Domain,
		"LE_EMAIL":      opts.Email,
		"SERVER_IP":     opts.ServerIP,
		"ADMIN_TOKEN":   opts.AdminToken,
		"DB_PASSWORD":   opts.DBPassword,
		"REGISTER_NODE": boolToYN(opts.RegisterNode),
		"NODE_NAME":     opts.NodeName,
		"NODE_MAX_KEYS": strconv.Itoa(opts.NodeMaxKeys),
		"RUN_NODE_HERE": boolToYN(opts.RunNodeHere),
		// install.sh's WEB_PANEL prompt (the optional SvelteKit+Bun admin
		// panel) defaults to "y" when left unset - fine for a human at a
		// keyboard, but this exec has no controlling terminal at all, so
		// install.sh's own read would fail and silently fall through to
		// that same default, meaning every app-initiated deploy would
		// attempt a Bun install and an npm build it never asked for,
		// slower and with its own new failure surface. Pinned to "n" (the
		// pre-existing embedded panel, unaffected either way) until this
		// app has a UI for it - see install.sh's WEB_PANEL for what "y"
		// would actually set up.
		"WEB_PANEL": "n",
	}

	var b strings.Builder
	b.WriteString("set -e; ")
	// raw.githubusercontent.com sits behind a CDN that caches a given URL
	// for a few minutes - a deploy retried right after a fix lands on the
	// default branch can otherwise still fetch the pre-fix script, making a
	// just-shipped fix look like it didn't take. A unique query string per
	// invocation is a different URL as far as the cache is concerned, so
	// every run always gets the current content.
	fmt.Fprintf(&b, "curl -fsSL %s -o /tmp/openflux-install.sh; ", shellQuote(cacheBust(scriptURL)))
	for _, key := range []string{
		"REPO_URL", "GIT_REF", "TLS_MODE", "DOMAIN", "LE_EMAIL", "SERVER_IP",
		"ADMIN_TOKEN", "DB_PASSWORD", "REGISTER_NODE", "NODE_NAME", "NODE_MAX_KEYS", "RUN_NODE_HERE",
		"WEB_PANEL",
	} {
		v := env[key]
		if v == "" {
			continue // unset: install.sh's own defaults/prompts-skipped-if-blank logic applies
		}
		fmt.Fprintf(&b, "export %s=%s; ", key, shellQuote(v))
	}
	b.WriteString("bash /tmp/openflux-install.sh")

	return b.String()
}

// cacheBust appends a timestamp query parameter so repeated deploys never
// reuse a CDN's cached response for scriptURL - see buildRemoteCommand.
func cacheBust(scriptURL string) string {
	sep := "?"
	if strings.Contains(scriptURL, "?") {
		sep = "&"
	}
	return fmt.Sprintf("%s%s_=%d", scriptURL, sep, time.Now().UnixNano())
}

func boolToYN(b bool) string {
	if b {
		return "y"
	}
	return "n"
}

// shellQuote wraps s in single quotes for safe interpolation into a POSIX
// shell command line, escaping any single quotes it contains.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

type noopCallback struct{}

func (noopCallback) OnLog(string)                          {}
func (noopCallback) OnHostKeyFingerprint(string)           {}
func (noopCallback) OnDeployResult(string, string, string) {}
