// Package deployssh runs deploy/install.sh on a remote VPS over SSH,
// non-interactively - see install.sh's ask/ask_secret helpers, which skip
// prompting for any variable already present in the environment. This
// package is the thing that pre-sets them all and streams the script's
// output back, one line at a time, via Callback.
package deployssh

import (
	"bufio"
	"fmt"
	"io"
	"net"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/ssh"
)

const (
	connectTimeout = 15 * time.Second
	deployTimeout  = 15 * time.Minute

	defaultDeployScriptURL = "https://raw.githubusercontent.com/wlruscfd/openflux-deploy/main/install.sh"
)

// SSHTarget describes how to reach and authenticate to the VPS.
type SSHTarget struct {
	Host     string
	Port     int
	Username string

	// AuthMethod is "password" or "key".
	AuthMethod    string
	Password      string
	PrivateKeyPEM string
	Passphrase    string // only used if PrivateKeyPEM is itself encrypted

	// KnownHostKeyFingerprint pins the server's host key (ssh.FingerprintSHA256
	// form) after a first successful connect. Leave empty on the very first
	// deploy to a given server; Callback.OnHostKeyFingerprint reports the
	// fingerprint to save for next time either way.
	KnownHostKeyFingerprint string
}

// DeployOptions mirrors install.sh's own questions - see deploy/install.sh's
// ask/ask_secret calls for the exact variable names these become.
type DeployOptions struct {
	// DeployScriptURL defaults to the openflux-deploy repo's raw install.sh
	// if left blank.
	DeployScriptURL string

	RepoURL string
	GitRef  string

	TLSMode  string // "domain" or "ip"
	Domain   string
	Email    string
	ServerIP string

	// AdminToken/DBPassword are generated by the caller (not left for
	// install.sh to invent) so it's known immediately, before the deploy
	// even starts - see mobile/deploy.go's caller for why.
	AdminToken string
	DBPassword string

	RegisterNode bool
	NodeName     string
	NodeMaxKeys  int
}

// Callback receives live progress from Deploy.
type Callback interface {
	// OnLog is called once per line of the remote script's stdout/stderr,
	// in order, as it's produced.
	OnLog(line string)
	// OnHostKeyFingerprint is called exactly once, right after the SSH
	// handshake completes, whether or not a KnownHostKeyFingerprint was
	// supplied - the caller should persist it for next time.
	OnHostKeyFingerprint(fingerprint string)
}

// Deploy connects to target and runs install.sh there with opts applied as
// pre-set environment variables, so none of the script's prompts fire. It
// blocks until the remote command finishes (or deployTimeout elapses) and
// returns a non-nil error if the script exited non-zero or the connection
// failed at any point.
func Deploy(target SSHTarget, opts DeployOptions, cb Callback) error {
	if cb == nil {
		cb = noopCallback{}
	}

	authMethod, err := buildAuthMethod(target)
	if err != nil {
		return fmt.Errorf("build ssh auth: %w", err)
	}

	var reportedFingerprint string
	config := &ssh.ClientConfig{
		User:    target.Username,
		Auth:    []ssh.AuthMethod{authMethod},
		Timeout: connectTimeout,
		HostKeyCallback: func(hostname string, remote net.Addr, key ssh.PublicKey) error {
			fp := ssh.FingerprintSHA256(key)
			reportedFingerprint = fp
			if target.KnownHostKeyFingerprint != "" && target.KnownHostKeyFingerprint != fp {
				return fmt.Errorf(
					"host key for %s changed: expected %s, got %s - remove and re-add this server if this is expected (rebuild, reinstall), otherwise treat this as a possible attack and do not proceed",
					hostname, target.KnownHostKeyFingerprint, fp,
				)
			}
			return nil
		},
	}

	addr := fmt.Sprintf("%s:%d", target.Host, target.Port)
	client, err := ssh.Dial("tcp", addr, config)
	if err != nil {
		return fmt.Errorf("ssh dial %s: %w", addr, err)
	}
	defer client.Close()

	cb.OnHostKeyFingerprint(reportedFingerprint)

	session, err := client.NewSession()
	if err != nil {
		return fmt.Errorf("open ssh session: %w", err)
	}
	defer session.Close()

	stdout, err := session.StdoutPipe()
	if err != nil {
		return fmt.Errorf("stdout pipe: %w", err)
	}
	stderr, err := session.StderrPipe()
	if err != nil {
		return fmt.Errorf("stderr pipe: %w", err)
	}

	remoteCmd := buildRemoteCommand(opts)

	if err := session.Start(remoteCmd); err != nil {
		return fmt.Errorf("start remote command: %w", err)
	}

	var wg sync.WaitGroup
	wg.Add(2)
	go streamLines(stdout, cb, &wg)
	go streamLines(stderr, cb, &wg)

	done := make(chan error, 1)
	go func() {
		wg.Wait()
		done <- session.Wait()
	}()

	select {
	case err := <-done:
		if err != nil {
			return fmt.Errorf("install.sh failed: %w", err)
		}
		return nil
	case <-time.After(deployTimeout):
		session.Signal(ssh.SIGKILL)
		return fmt.Errorf("deploy timed out after %s", deployTimeout)
	}
}

func buildAuthMethod(target SSHTarget) (ssh.AuthMethod, error) {
	switch target.AuthMethod {
	case "key":
		var signer ssh.Signer
		var err error
		if target.Passphrase != "" {
			signer, err = ssh.ParsePrivateKeyWithPassphrase([]byte(target.PrivateKeyPEM), []byte(target.Passphrase))
		} else {
			signer, err = ssh.ParsePrivateKey([]byte(target.PrivateKeyPEM))
		}
		if err != nil {
			return nil, fmt.Errorf("parse private key: %w", err)
		}
		return ssh.PublicKeys(signer), nil
	case "password", "":
		return ssh.Password(target.Password), nil
	default:
		return nil, fmt.Errorf("unknown auth method %q", target.AuthMethod)
	}
}

func streamLines(r io.Reader, cb Callback, wg *sync.WaitGroup) {
	defer wg.Done()
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		cb.OnLog(scanner.Text())
	}
}

// buildRemoteCommand fetches install.sh and runs it with every DeployOptions
// field pre-exported (shell-quoted) so its ask/ask_secret helpers never
// prompt - see deploy/install.sh.
func buildRemoteCommand(opts DeployOptions) string {
	scriptURL := opts.DeployScriptURL
	if scriptURL == "" {
		scriptURL = defaultDeployScriptURL
	}

	env := map[string]string{
		"REPO_URL":      opts.RepoURL,
		"GIT_REF":       opts.GitRef,
		"TLS_MODE":      opts.TLSMode,
		"DOMAIN":        opts.Domain,
		"LE_EMAIL":      opts.Email,
		"SERVER_IP":     opts.ServerIP,
		"ADMIN_TOKEN":   opts.AdminToken,
		"DB_PASSWORD":   opts.DBPassword,
		"REGISTER_NODE": boolToYN(opts.RegisterNode),
		"NODE_NAME":     opts.NodeName,
		"NODE_MAX_KEYS": strconv.Itoa(opts.NodeMaxKeys),
	}

	var b strings.Builder
	b.WriteString("set -e; ")
	fmt.Fprintf(&b, "curl -fsSL %s -o /tmp/openflux-install.sh; ", shellQuote(scriptURL))
	for _, key := range []string{
		"REPO_URL", "GIT_REF", "TLS_MODE", "DOMAIN", "LE_EMAIL", "SERVER_IP",
		"ADMIN_TOKEN", "DB_PASSWORD", "REGISTER_NODE", "NODE_NAME", "NODE_MAX_KEYS",
	} {
		v := env[key]
		if v == "" {
			continue // unset: install.sh's own defaults/prompts-skipped-if-blank logic applies
		}
		fmt.Fprintf(&b, "export %s=%s; ", key, shellQuote(v))
	}
	b.WriteString("bash /tmp/openflux-install.sh")

	return b.String()
}

func boolToYN(b bool) string {
	if b {
		return "y"
	}
	return "n"
}

// shellQuote wraps s in single quotes for safe interpolation into a POSIX
// shell command line, escaping any single quotes it contains.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

type noopCallback struct{}

func (noopCallback) OnLog(string)                {}
func (noopCallback) OnHostKeyFingerprint(string) {}
